services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Maps localhost:27017 to container:27017
    volumes:
      - mongo-data:/data/db # Persists data to a local volume

volumes:
  mongo-data: